#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */

/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[211] =
    {   0,
        0,    0,   66,   64,   60,   60,   64,   62,   49,   64,
       59,   59,   59,   48,   59,   59,   59,   59,   55,   59,
       53,   55,   53,   55,   59,   59,   59,   60,    0,    0,
        0,   62,    0,    0,    0,    0,    0,    0,    0,   18,
       20,    0,    0,    0,   52,   52,   63,   59,   59,   59,
       59,   54,   59,   59,    5,   59,   59,   59,   59,   59,
       54,   59,   59,   59,   59,   59,   10,   59,   59,   59,
       59,   54,   59,    0,   56,    0,    0,    0,    0,   33,
        0,   42,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   52,    0,   52,    0,   63,   58,   58,   16,

       59,   59,   59,   56,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   11,
        7,   50,   59,   59,   59,   59,   52,   46,    0,    0,
        0,    0,   35,   29,    0,    0,   30,    0,    0,    0,
       21,    0,   31,    0,   61,   59,   59,   59,    6,   51,
       57,   59,    4,   57,   59,   59,   13,   59,   59,   32,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   17,
        0,    9,   15,   45,   37,    1,   34,   47,   36,   61,
        2,   22,    3,   43,   28,   59,   14,   59,   59,   26,
       24,   40,   12,   59,   59,   25,   23,   59,    0,   27,

       38,   19,   59,   39,   59,   44,   59,   41,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    1,
        1,    8,    1,    1,    9,    1,   10,   11,   11,   12,
       13,   11,   11,   11,   11,   11,   11,    1,    1,    1,
       14,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       24,   31,   32,   33,   34,   35,   36,   37,   38,   39,
        1,    1,    1,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   24,   50,   51,   52,   53,
       54,   55,   24,   56,   57,   58,   59,   60,   61,   62,
       63,   64,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   24,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   24,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   24,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    3,    4,    1,    5,    2,    1,    6,
        7,    7,    7,    1,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7
    } ;

static const flex_int16_t yy_base[221] =
    {   0,
        0,    0,  167, 1224,   63,   66,   70,    0,   96,   77,
       78,   85,   95, 1224,   81,  145,  181,  121,  158,  226,
      135,  161,  275,  166,  205,  215,  251,   97,  161,    0,
      335,    0,   68,   66,  117,  176,  107,  142,  168,  169,
      130,  164,  185,  226,  149,  285,    0,  240,  265,  319,
      341,  310,  344,  392,  349,  352,  357,  375,  396,  411,
      405,  414,  436,  445,  492,  457,  460,  483,  541,  500,
      537,  467, 1224,   99,  145,  170,  203,  208,  248, 1224,
      239, 1224,  255,  251,  217,  268,  263,  273,  279,  275,
      327,  134,  309,  115,  112,  433,    0,  471,  516,  550,

      561,  574,  586,  567,  597,  608,  600,  630,  641,  623,
      653,  656,  660,  666,  679,  692,  705,  714,  726,  717,
      729,  739,  749,  752,  762,  774, 1224, 1224,  333,  348,
      338,  355, 1224, 1224,  366,  407, 1224,  418,  416,  444,
     1224,  417, 1224,   93,   92,  765,  798,  811,  814,  818,
      821,  832,  835,  854,  857,  865,  868,  875,  878,  890,
      908,  914,  900,  924,  938,  944,  949,  954,  969, 1224,
      432, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224,
      975,  979,  984,  994, 1000, 1005, 1009, 1014, 1031, 1018,
     1035, 1040, 1044, 1048, 1057, 1061, 1066, 1074,  469, 1078,

     1083, 1092, 1097, 1100, 1108, 1224, 1104, 1118, 1122, 1224,
     1167, 1174, 1181,   81,   68, 1188, 1195, 1202, 1209, 1216
    } ;

static const flex_int16_t yy_def[221] =
    {   0,
      210,    1,  210,  210,  210,  210,  211,  212,  210,  213,
      214,  214,  214,  210,  214,  214,  214,  215,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  210,  216,  217,
      211,  212,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  213,  218,  219,  214,  214,  214,
      214,  214,  214,  214,  214,  215,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,   65,
      214,  214,  210,  217,  216,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  213,  218,  220,  213,  218,  219,  214,  214,  214,

      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  213,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  210,  214,

      214,  214,  214,  214,  214,  210,  214,  214,  214,    0,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210
    } ;

static const flex_int16_t yy_nxt[1289] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    4,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       15,   15,   15,   15,   21,   22,   23,   15,   15,   24,
       25,   15,   15,   26,   18,   27,   15,   15,   15,   11,
       15,   16,   17,   18,   19,   20,   15,   15,   15,   21,
       22,   23,   15,   15,   24,   25,   15,   15,   26,   18,
       27,   15,   15,   15,   28,   28,   28,   28,   28,   28,
       29,   29,   29,   29,   56,   29,   29,   29,   29,   30,
       29,   29,   29,   29,   46,   76,   47,   49,   48,   48,
       48,   48,   48,   48,   77,   48,   48,   48,   28,   28,

       28,  210,  180,  127,   50,   48,   48,   48,   30,   29,
       33,   76,   34,   35,   51,   36,   37,   48,   38,   77,
       48,  145,  144,   39,   48,   40,   41,   42,   43,   44,
       50,   48,   48,   48,   48,   78,   33,   81,   34,   35,
       51,   36,   37,  210,   38,   48,   48,   48,   39,   73,
       40,   41,   42,   43,   44,   48,   48,   48,   92,   82,
       48,   78,   81,   86,   52,   73,  210,  210,   48,   48,
       48,   48,   48,   48,   48,   57,   48,   48,   48,  210,
       68,  210,   83,   84,   48,   82,   87,  128,   86,   64,
       52,   48,   48,   48,   58,   53,  210,   48,   79,  210,

       48,   57,   54,  210,   85,   48,   68,   80,   83,   84,
       55,  210,   87,  128,   64,   48,   48,   48,  210,   58,
       48,   53,   88,   69,   79,   48,   48,   48,   54,   85,
      129,   70,   80,  130,  137,   55,   48,   48,   48,  131,
       59,  210,   71,   60,   48,   61,   89,   88,   62,   69,
       48,   48,   48,   90,   48,  129,   70,   91,  130,   63,
      137,   48,   48,   48,  131,   48,   59,   71,  134,   60,
       72,   61,   89,  132,   62,   48,   48,   48,   90,   48,
      133,  135,   91,  136,   63,   48,   48,   48,   94,   94,
       48,   45,   95,  134,   96,  210,   72,  142,  132,   65,

      138,  139,  140,   66,   48,  133,  135,  141,  136,   67,
      210,  210,   94,   94,   48,   45,   95,  210,   96,  210,
       48,   48,   48,  142,   65,  138,  139,  140,   66,   48,
       48,   48,  141,  210,   67,   29,   29,   29,   29,   73,
       29,   29,   29,   29,  210,   75,   75,   75,   29,   48,
       98,   48,   48,   48,   48,   48,   48,  143,   48,   48,
       48,   48,  104,  104,  104,  170,  171,   48,   48,   48,
      172,  210,   99,  173,   29,   98,  100,  210,  210,  105,
       48,  210,  143,   48,  174,   48,   48,   48,   48,  210,
      170,   48,  171,  106,  210,  172,   48,   99,  210,  173,

      210,  100,   48,   48,   48,  105,   48,   48,   48,  210,
      174,  210,  101,  210,   48,   48,   48,   48,  102,  106,
      103,   48,   48,   48,   48,   48,   48,  107,  175,  210,
      210,   48,  176,  108,  177,   48,   94,   94,  101,   45,
       95,  109,   94,  102,   48,  103,   48,   48,   48,  179,
       48,  210,  107,   48,  175,   48,   48,   48,  176,  108,
      177,  110,  178,  210,  199,  111,  109,   48,   48,   48,
       48,   48,   48,  210,  179,   48,  112,   48,   48,   48,
      210,   48,   48,   48,   48,  210,  110,  206,  178,  199,
      117,  111,  210,   48,   48,   48,   48,  210,  210,   48,

      210,  112,   48,   48,   48,  210,   48,  210,  210,  113,
       48,  114,  115,  206,  210,  117,  118,  123,  210,   49,
      124,  210,   48,  210,  210,  116,   48,   48,   48,  210,
      210,   48,  210,  125,  210,  113,  210,  114,  115,  210,
      210,  118,  210,  123,  210,   49,  124,   48,   48,   48,
      116,   48,   48,   48,  210,   48,  210,  119,  125,  210,
       48,   48,   48,  126,  210,  210,  210,  120,  121,  210,
      122,   48,   48,   48,  210,  210,   48,   48,   48,   48,
       48,  210,  210,  119,   48,   48,   48,  210,  126,   48,
      210,  146,  120,  121,  210,  122,   48,   48,   48,  210,

       48,  210,  147,  210,  210,  210,   48,   48,   48,   48,
       48,   48,   48,   48,  210,  210,  146,  210,   48,   48,
       48,  148,  210,  210,  150,   48,  210,  147,  210,  149,
      210,  210,  151,   48,   48,   48,   48,  210,  210,   48,
       48,   48,   48,  210,  210,  210,  148,   48,  154,  210,
      150,   48,   48,   48,  149,  210,  210,  151,  153,  210,
      210,  152,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,  154,  210,  155,   48,   48,   48,  210,
       48,  156,  158,  210,  153,  210,  152,  157,  159,   48,
       48,   48,   48,  210,  210,   48,  210,  160,  210,   48,

      210,  155,   48,   48,   48,   48,  156,  210,  158,  161,
      210,  210,  157,  210,  159,   48,   48,   48,   48,  210,
      210,  210,  160,  162,   48,   48,   48,   48,   48,   48,
      210,   48,  163,  210,  161,  210,   48,   48,   48,   48,
       48,   48,  210,  210,   48,  164,  210,  210,  162,   48,
       48,   48,  210,   48,  165,  210,   48,  163,  210,   48,
       48,   48,   48,   48,   48,   48,  210,  210,   48,  210,
      164,  166,   48,   48,   48,   48,   48,   48,   48,  165,
      210,  210,  167,  210,   48,   48,   48,  210,   48,  210,
      210,   48,  210,  168,  181,  210,  210,  166,  210,  210,

      210,   48,  169,  210,   48,  210,  210,  167,   48,   48,
       48,  210,  210,   48,  210,  182,  210,  210,  168,  181,
      210,   48,   48,   48,   48,   48,   48,  169,   48,   48,
       48,   48,   48,   48,  210,  210,  210,   48,  183,  210,
      210,  182,   48,   48,   48,   48,   48,   48,  210,  210,
       48,  210,  210,   48,  210,  210,  184,   48,  210,  210,
       48,  210,  210,  183,   48,   48,   48,   48,   48,   48,
      210,   48,  210,  210,   48,   48,   48,   48,   48,   48,
       48,  184,  210,  210,  185,   48,   48,   48,   48,   48,
       48,  210,  210,   48,  210,  210,   48,  210,  186,  210,

       48,   48,   48,  189,   48,  187,  188,   48,  210,  185,
       48,   48,   48,  210,   48,  210,  210,   48,   48,   48,
       48,  210,  210,  186,   48,   48,   48,  210,  189,   48,
      187,  188,  192,  210,   48,   48,   48,  190,  210,   48,
      210,  210,  193,  210,  191,  210,  210,   48,   48,   48,
       48,  210,  210,   48,   48,   48,   48,  192,  210,   48,
       48,   48,  190,   48,   48,   48,   48,  210,  193,  191,
      210,  210,  194,  210,  210,  195,  210,   48,  196,   48,
       48,   48,  210,   48,  197,   48,   48,   48,   48,   48,
       48,   48,  210,   48,   48,   48,   48,  194,  210,  210,

      195,  210,  198,  196,   48,   48,   48,  210,   48,  197,
       48,   48,   48,  210,   48,   48,   48,   48,   48,   48,
       48,   48,  210,   48,   48,   48,   48,  198,   48,   48,
       48,  210,  210,   48,  210,  210,  210,  200,  201,   48,
      210,   48,   48,   48,   48,   48,   48,   48,   48,  202,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,  210,  200,  201,  210,  210,  203,   48,   48,   48,
       48,   48,   48,   48,   48,  202,   48,   48,   48,   48,
      210,  204,  210,   48,   48,   48,   48,   48,   48,   48,
       48,  210,  203,   48,   48,   48,   48,  210,  210,  210,

       48,  205,   48,   48,   48,   48,  204,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,  210,   48,  210,  210,  210,  205,  207,   48,   48,
       48,   48,   48,   48,   48,  210,   48,  210,  210,   48,
      208,  209,  210,   48,  210,  210,  210,   48,  210,  210,
      210,  210,  207,  210,  210,  210,  210,   48,  210,  210,
      210,   48,  210,  210,  210,  208,  209,   31,   31,   31,
      210,   31,   31,   31,   32,  210,   32,   32,   32,   32,
       32,   45,   45,  210,  210,   45,   45,   45,   29,   29,
       29,   29,   29,  210,   29,   74,   74,   74,  210,   74,

      210,   74,   93,   93,   93,   93,   93,   93,   93,   97,
      210,   97,   97,   97,   97,   97,   94,   94,   94,   94,
      210,   94,   94,    3,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210
    } ;

static const flex_int16_t yy_chk[1289] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    6,    6,    6,
        7,    7,    7,    7,  215,    7,    7,    7,    7,    7,
        7,    7,    7,    7,   10,   33,   10,  214,   11,   11,
       11,   15,   15,   15,   34,   12,   12,   12,   28,   28,

       28,  145,  144,   74,   12,   13,   13,   13,   74,    7,
        9,   33,    9,    9,   13,    9,    9,   11,    9,   34,
       15,   95,   94,    9,   12,    9,    9,    9,    9,    9,
       12,   18,   18,   18,   13,   35,    9,   37,    9,    9,
       13,    9,    9,   92,    9,   21,   21,   21,    9,   75,
        9,    9,    9,    9,    9,   16,   16,   16,   45,   38,
       18,   35,   37,   41,   16,   29,    3,    0,   19,   19,
       19,   22,   22,   22,   21,   19,   24,   24,   24,    0,
       24,    0,   39,   40,   16,   38,   42,   76,   41,   22,
       16,   17,   17,   17,   19,   17,    0,   19,   36,    0,

       22,   19,   17,    0,   40,   24,   24,   36,   39,   40,
       17,    0,   42,   76,   22,   25,   25,   25,    0,   19,
       17,   17,   43,   25,   36,   26,   26,   26,   17,   40,
       77,   25,   36,   78,   85,   17,   20,   20,   20,   78,
       20,    0,   26,   20,   25,   20,   44,   43,   20,   25,
       48,   48,   48,   44,   26,   77,   25,   44,   78,   20,
       85,   27,   27,   27,   78,   20,   20,   26,   81,   20,
       27,   20,   44,   79,   20,   49,   49,   49,   44,   48,
       79,   83,   44,   84,   20,   23,   23,   23,   46,   46,
       27,   46,   46,   81,   46,    0,   27,   90,   79,   23,

       86,   87,   88,   23,   49,   79,   83,   89,   84,   23,
        0,    0,   93,   93,   23,   93,   93,    0,   93,    0,
       52,   52,   52,   90,   23,   86,   87,   88,   23,   50,
       50,   50,   89,    0,   23,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   52,
       50,   51,   51,   51,   53,   53,   53,   91,   50,   55,
       55,   55,   56,   56,   56,  129,  130,   57,   57,   57,
      131,    0,   51,  132,   31,   50,   53,    0,    0,   57,
       51,    0,   91,   53,  135,   58,   58,   58,   55,    0,
      129,   56,  130,   58,    0,  131,   57,   51,    0,  132,

        0,   53,   54,   54,   54,   57,   59,   59,   59,    0,
      135,    0,   54,    0,   58,   61,   61,   61,   54,   58,
       54,   60,   60,   60,   62,   62,   62,   59,  136,    0,
        0,   54,  138,   60,  139,   59,   96,   96,   54,   96,
       96,   62,   96,   54,   61,   54,   63,   63,   63,  142,
       60,    0,   59,   62,  136,   64,   64,   64,  138,   60,
      139,   63,  140,    0,  171,   64,   62,   66,   66,   66,
       67,   67,   67,    0,  142,   63,   64,   72,   72,   72,
        0,   98,   98,   98,   64,    0,   63,  199,  140,  171,
       66,   64,    0,   68,   68,   68,   66,    0,    0,   67,

        0,   64,   65,   65,   65,    0,   72,    0,    0,   65,
       98,   65,   65,  199,    0,   66,   68,   70,    0,   70,
       70,    0,   68,    0,    0,   65,   99,   99,   99,    0,
        0,   65,    0,   70,    0,   65,    0,   65,   65,    0,
        0,   68,    0,   70,    0,   70,   70,   71,   71,   71,
       65,   69,   69,   69,    0,   99,    0,   69,   70,    0,
      100,  100,  100,   71,    0,    0,    0,   69,   69,    0,
       69,  101,  101,  101,    0,    0,   71,  104,  104,  104,
       69,    0,    0,   69,  102,  102,  102,    0,   71,  100,
        0,  101,   69,   69,    0,   69,  103,  103,  103,    0,

      101,    0,  102,    0,    0,    0,  104,  105,  105,  105,
      107,  107,  107,  102,    0,    0,  101,    0,  106,  106,
      106,  103,    0,    0,  106,  103,    0,  102,    0,  105,
        0,    0,  107,  110,  110,  110,  105,    0,    0,  107,
      108,  108,  108,    0,    0,    0,  103,  106,  110,    0,
      106,  109,  109,  109,  105,    0,    0,  107,  109,    0,
        0,  108,  110,  111,  111,  111,  112,  112,  112,  108,
      113,  113,  113,  110,    0,  111,  114,  114,  114,    0,
      109,  111,  113,    0,  109,    0,  108,  112,  114,  115,
      115,  115,  111,    0,    0,  112,    0,  114,    0,  113,

        0,  111,  116,  116,  116,  114,  111,    0,  113,  115,
        0,    0,  112,    0,  114,  117,  117,  117,  115,    0,
        0,    0,  114,  116,  118,  118,  118,  120,  120,  120,
        0,  116,  117,    0,  115,    0,  119,  119,  119,  121,
      121,  121,    0,    0,  117,  118,    0,    0,  116,  122,
      122,  122,    0,  118,  119,    0,  120,  117,    0,  123,
      123,  123,  124,  124,  124,  119,    0,    0,  121,    0,
      118,  123,  125,  125,  125,  146,  146,  146,  122,  119,
        0,    0,  124,    0,  126,  126,  126,    0,  123,    0,
        0,  124,    0,  125,  146,    0,    0,  123,    0,    0,

        0,  125,  126,    0,  146,    0,    0,  124,  147,  147,
      147,    0,    0,  126,    0,  147,    0,    0,  125,  146,
        0,  148,  148,  148,  149,  149,  149,  126,  150,  150,
      150,  151,  151,  151,    0,    0,    0,  147,  148,    0,
        0,  147,  152,  152,  152,  153,  153,  153,    0,    0,
      148,    0,    0,  149,    0,    0,  152,  150,    0,    0,
      151,    0,    0,  148,  154,  154,  154,  155,  155,  155,
        0,  152,    0,    0,  153,  156,  156,  156,  157,  157,
      157,  152,    0,    0,  155,  158,  158,  158,  159,  159,
      159,    0,    0,  154,    0,    0,  155,    0,  156,    0,

      160,  160,  160,  159,  156,  158,  158,  157,    0,  155,
      163,  163,  163,    0,  158,    0,    0,  159,  161,  161,
      161,    0,    0,  156,  162,  162,  162,    0,  159,  160,
      158,  158,  163,    0,  164,  164,  164,  161,    0,  163,
        0,    0,  164,    0,  162,    0,    0,  161,  165,  165,
      165,    0,    0,  162,  166,  166,  166,  163,    0,  167,
      167,  167,  161,  164,  168,  168,  168,    0,  164,  162,
        0,    0,  165,    0,    0,  166,    0,  165,  167,  169,
      169,  169,    0,  166,  168,  181,  181,  181,  167,  182,
      182,  182,    0,  168,  183,  183,  183,  165,    0,    0,

      166,    0,  169,  167,  184,  184,  184,    0,  169,  168,
      185,  185,  185,    0,  181,  186,  186,  186,  182,  187,
      187,  187,    0,  183,  188,  188,  188,  169,  190,  190,
      190,    0,    0,  184,    0,    0,    0,  186,  188,  185,
        0,  189,  189,  189,  186,  191,  191,  191,  187,  189,
      192,  192,  192,  188,  193,  193,  193,  190,  194,  194,
      194,    0,  186,  188,    0,    0,  194,  195,  195,  195,
      189,  196,  196,  196,  191,  189,  197,  197,  197,  192,
        0,  195,    0,  193,  198,  198,  198,  194,  200,  200,
      200,    0,  194,  201,  201,  201,  195,    0,    0,    0,

      196,  198,  202,  202,  202,  197,  195,  203,  203,  203,
      204,  204,  204,  198,  207,  207,  207,  200,  205,  205,
      205,    0,  201,    0,    0,    0,  198,  203,  208,  208,
      208,  202,  209,  209,  209,    0,  203,    0,    0,  204,
      205,  207,    0,  207,    0,    0,    0,  205,    0,    0,
        0,    0,  203,    0,    0,    0,    0,  208,    0,    0,
        0,  209,    0,    0,    0,  205,  207,  211,  211,  211,
        0,  211,  211,  211,  212,    0,  212,  212,  212,  212,
      212,  213,  213,    0,    0,  213,  213,  213,  216,  216,
      216,  216,  216,    0,  216,  217,  217,  217,    0,  217,

        0,  217,  218,  218,  218,  218,  218,  218,  218,  219,
        0,  219,  219,  219,  219,  219,  220,  220,  220,  220,
        0,  220,  220,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[65] =
    {   0,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
       77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
       87,   88,   89,   90,   91,   92,   93,   94,   95,   97,
       98,   99,  100,  102
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.l"
#line 2 "lexico.l"
# include <cerrno>
#include <stdio.h>
#include <string>
#include "driver.h"
#include "parser.tab.hh"
#undef yywrap
#define yywrap() 1
static yy::location loc;
#line 898 "scanner.cpp"
#define YY_NO_INPUT 1
#line 900 "scanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals ( void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 35 "lexico.l"


#line 1181 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 211 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 210 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 65 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 65 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 66 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "lexico.l"
{return yy::analizer_parser::make_ruta(yytext, loc);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "lexico.l"
{return yy::analizer_parser::make_chgrp(yytext, loc);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "lexico.l"
{return yy::analizer_parser::make_chown(yytext, loc);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "lexico.l"
{return yy::analizer_parser::make_find(yytext, loc);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "lexico.l"
{return yy::analizer_parser::make_cp(yytext, loc);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "lexico.l"
{return yy::analizer_parser::make_edit(yytext, loc);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "lexico.l"
{return yy::analizer_parser::make_ren(yytext, loc);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "lexico.l"
{return yy::analizer_parser::make_recovery(yytext, loc);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "lexico.l"
{return yy::analizer_parser::make_dest(yytext, loc);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "lexico.l"
{return yy::analizer_parser::make_mv(yytext, loc);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "lexico.l"
{return yy::analizer_parser::make_rem(yytext, loc);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "lexico.l"
{return yy::analizer_parser::make_pause(yytext, loc);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "lexico.l"
{return yy::analizer_parser::make_loss(yytext, loc);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "lexico.l"
{return yy::analizer_parser::make_mkdir(yytext, loc);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 51 "lexico.l"
{return yy::analizer_parser::make_file(yytext, loc);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 52 "lexico.l"
{return yy::analizer_parser::make_cat(yytext, loc);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "lexico.l"
{return yy::analizer_parser::make_cont(yytext, loc);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "lexico.l"
{return yy::analizer_parser::make_parametro(yytext, loc);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "lexico.l"
{return yy::analizer_parser::make_mkFile(yytext, loc);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "lexico.l"
{return yy::analizer_parser::make_recursive(yytext, loc);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "lexico.l"
{return yy::analizer_parser::make_ugo(yytext, loc);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "lexico.l"
{return yy::analizer_parser::make_chmod(yytext, loc);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "lexico.l"
{return yy::analizer_parser::make_rmusr(yytext, loc);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "lexico.l"
{return yy::analizer_parser::make_mkusr(yytext, loc);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "lexico.l"
{return yy::analizer_parser::make_rmgrp(yytext, loc);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "lexico.l"
{return yy::analizer_parser::make_mkgrp(yytext, loc);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "lexico.l"
{return yy::analizer_parser::make_logout(yytext, loc);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "lexico.l"
{return yy::analizer_parser::make_login(yytext, loc);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "lexico.l"
{return yy::analizer_parser::make_grp(yytext, loc);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 66 "lexico.l"
{return yy::analizer_parser::make_pwd(yytext, loc);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 67 "lexico.l"
{return yy::analizer_parser::make_usr(yytext, loc);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 68 "lexico.l"
{return yy::analizer_parser::make_mkfs(yytext, loc);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 69 "lexico.l"
{return yy::analizer_parser::make_fs(yytext, loc);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 70 "lexico.l"
{return yy::analizer_parser::make_size(yytext, loc);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "lexico.l"
{return yy::analizer_parser::make_fit(yytext, loc);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 72 "lexico.l"
{return yy::analizer_parser::make_unit(yytext, loc);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "lexico.l"
{return yy::analizer_parser::make_path(yytext, loc);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "lexico.l"
{return yy::analizer_parser::make_mkdisk(yytext, loc);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "lexico.l"
{return yy::analizer_parser::make_rmdisk(yytext, loc);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "lexico.l"
{return yy::analizer_parser::make_mount(yytext, loc);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "lexico.l"
{return yy::analizer_parser::make_unmount(yytext, loc);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "lexico.l"
{return yy::analizer_parser::make_id(yytext, loc);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "lexico.l"
{return yy::analizer_parser::make_fdisk(yytext, loc);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "lexico.l"
{return yy::analizer_parser::make_deleter(yytext, loc);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "lexico.l"
{return yy::analizer_parser::make_name(yytext, loc);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "lexico.l"
{return yy::analizer_parser::make_add(yytext, loc);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "lexico.l"
{return yy::analizer_parser::make_typer(yytext, loc);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 84 "lexico.l"
{return yy::analizer_parser::make_assign(yytext, loc);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "lexico.l"
{return yy::analizer_parser::make_minus(yytext, loc);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 86 "lexico.l"
{return yy::analizer_parser::make_rep(yytext, loc);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 87 "lexico.l"
{return yy::analizer_parser::make_exec(yytext, loc);}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 88 "lexico.l"
{return yy::analizer_parser::make_pather(yytext, loc);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 89 "lexico.l"
{return yy::analizer_parser::make_unitl(yytext[0], loc);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 90 "lexico.l"
{return yy::analizer_parser::make_adj(yytext, loc);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 91 "lexico.l"
{return yy::analizer_parser::make_typep(yytext[0], loc);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 92 "lexico.l"
{return yy::analizer_parser::make_idvda(yytext, loc);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 93 "lexico.l"
{return yy::analizer_parser::make_tpdelete(yytext, loc);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 94 "lexico.l"
{return yy::analizer_parser::make_typartition(yytext, loc);}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 95 "lexico.l"
{return yy::analizer_parser::make_npart(yytext, loc);}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 97 "lexico.l"
{}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 98 "lexico.l"
{}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 99 "lexico.l"
{}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 100 "lexico.l"
{}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "lexico.l"
{printf("ERROR LEXICO %s\n",yytext);}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 103 "lexico.l"
{return yy::analizer_parser::make_FIN(loc);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 104 "lexico.l"
ECHO;
	YY_BREAK
#line 1590 "scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 211 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 211 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 210);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 104 "lexico.l"

void analizer_driver::iniciarScanner()
{

    yy_scan_string(file.c_str());
/*
    yy_flex_debug = false;
    if(file.empty() || file == "-"){
      std::cout << "No se encuentra el archivo de entrada \n";
      exit(1);
    }else{
      yyin = fopen (file.c_str (), "r");
    }

*/
}

void analizer_driver::terminarScanner()
{
    fclose(yyin);
}

